import React from 'react'; import Defaultnavbar from './navbar'; import './site.css'; import resumePdf from './liyander_new.pdf';
const skills=['AWS','Azure','IAM','Kubernetes','Docker','Terraform','Jenkins','Prometheus','Grafana','Burp Suite Pro','Metasploit','Nmap','Nessus','Wireshark','Splunk','Ghidra','Python','JavaScript','Bash','PowerShell','React','Node.js','Flask','MongoDB','MySQL'];
export default function Resume(){return <div className="page-wrap resume-page"><Defaultnavbar/><main className="page-main resume-layout">
  <aside className="resume-aside"><span className="kicker">04 / PERSONNEL FILE</span><div className="identity-orbit"><span>LR</span><i></i></div><h1>Liyander<br/>Rishwanth L.</h1><p>Security Engineer / Cloud Security & DevSecOps / Vulnerability Research</p><div className="resume-numbers"><span><b>18</b> CVEs</span><span><b>10.0</b> max CVSS</span><span><b>8.6</b> GPA</span></div><a className="download-button" href={resumePdf} download>DOWNLOAD RESUME <span>+</span></a><div className="contact-list"><a href="mailto:liyanderrishwanth18@gmail.com">Email</a><a href="https://www.linkedin.com/in/liyanderrishwanth/" target="_blank" rel="noreferrer">LinkedIn</a><a href="https://github.com/liyander" target="_blank" rel="noreferrer">GitHub</a><a href="https://profile.hackthebox.com/profile/019c4ab6-e83a-7264-831b-ebfa22acf909" target="_blank" rel="noreferrer">Hack The Box</a></div></aside>
  <div className="dossier">
    <section className="resume-section"><header><span>01</span><h2>Profile</h2></header><p className="resume-lead">Security engineer specializing in cloud security, DevSecOps, application security, and offensive research. Published 18 CVEs - including a maximum-severity remote-code-execution finding - with acknowledgments from Apple, Microsoft, Oracle, and Google.</p><div className="recognition">INVITED / MSRC RESEARCHER CELEBRATION / BLACK HAT USA 2026</div></section>
    <section className="resume-section"><header><span>02</span><h2>Experience</h2></header><article className="resume-item"><div><small>MAR 2026 - PRESENT / REMOTE</small><h3>Security Engineering Intern</h3><b>Black Pearl DFIR</b></div><ul><li>Engineered a centralized threat intelligence dashboard across five critical networks and systems.</li><li>Reduced incident resolution time by 30% and saved 15 hours weekly through response automation.</li></ul></article><article className="resume-item"><div><small>DEC 2025 - JAN 2026</small><h3>Cybersecurity Intern</h3><b>Indian Space Research Organisation</b></div><ul><li>Performed risk assessments across six secured aerospace network segments.</li><li>Improved workflow efficiency by 25% and authored ten incident response protocols.</li></ul></article></section>
    <section className="resume-section"><header><span>03</span><h2>Vulnerability research</h2></header><div className="cve-grid"><article><b>CVE-2026-43678</b><p>Apple Swift-NIO WebSocket decoder remote crash.</p></article><article><b>CVE-2026-33054 / 33057</b><p>Google Mesop AI path traversal and remote code execution.</p></article><article><b>CVE-2026-50137</b><p>Budibase authorization bypass and credential exposure.</p></article><article><b>CVE-2026-35441</b><p>Directus CMS access-control and availability flaw.</p></article></div></section>
    <section className="resume-section"><header><span>04</span><h2>Technical toolkit</h2></header><div className="skill-chips">{skills.map((s,i)=><span key={s}>{String(i+1).padStart(2,'0')} / {s}</span>)}</div></section>
    <section className="resume-section"><header><span>05</span><h2>Education</h2></header><article className="education-card"><div><small>2023 - 2027</small><h3>B.Tech Computer Science & Engineering</h3><p>Cybersecurity / Sri Shakthi Institute of Engineering and Technology</p></div><strong>8.6<span>/10</span></strong></article></section>
  </div>
</main></div>}
